### ISSUE TITLE
false values don't show in inspect

### ISSUE THREAD

**Issue by kunruh9** [data-axle/superstore#35]
```ruby
class TestSuperstore < Superstore::Base
    boolean :foo
end

t = TestSuperstore.new
t.foo = true
puts t.inspect
#<TestSuperstore id: "7fe85c78e7fa417ebc6a7aec321fecc0", foo: true>
t.foo = false
puts t.inspect
#<TestSuperstore id: "7fe85c78e7fa417ebc6a7aec321fecc0">
```

Looks like this is because `false.present? == false`, as used [here](https://github.com/data-axle/superstore/blob/master/lib/superstore/inspect.rb#L7). Is this intentional?

**Comment by matthuhiggins** [comment]
Nice

**Comment by kunruh9** [comment]
> Nice

I'm going to take that as "no, not intentional, feel free to fix" 👍

**Comment by matthuhiggins** [comment]
Oops, I thought this was a pull request with the fix.
